name: Smart System CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
      
permissions:
  contents: read
  packages: write

jobs:
  test-and-build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout repository
       uses: actions/checkout@v4 
     - name: Setup Node.js
       uses: actions/setup-node@v4
       with:
          node-version: 20
          cache: npm 
     - name: Install dependencies
       run: npm ci
     - name: Run lint
       run: npm run lint
     - name: Run tests
       run: npm test
     - name: Build Next.js application
       run: npm run build
     - name: Build Docker image
       run: docker build -t smart-system:test .
     - name: log in to github container registry
       uses: docker/login-action@v3
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}
     - name: tag Docker image
       run: docker tag smart-system:test ghcr.io/${{ github.repository_owner }}/smart-system:latest
     - name: push Docker image
       run: docker push ghcr.io/${{ github.repository_owner }}/smart-system:latest